from enum import StrEnum


class ApplicationState(StrEnum):
    RECEIVED = "RECEIVED"
    DOCUMENT_CHECK = "DOCUMENT_CHECK"
    INCOME_VERIFICATION = "INCOME_VERIFICATION"
    CREDIT_ANALYSIS = "CREDIT_ANALYSIS"
    RISK_ASSESSMENT = "RISK_ASSESSMENT"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    DECISION = "DECISION"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    MORE_INFORMATION_REQUIRED = "MORE_INFORMATION_REQUIRED"
    FAILED = "FAILED"


class Actor(StrEnum):
    SYSTEM = "SYSTEM"
    AGENT = "AGENT"
    APPLICANT = "APPLICANT"
    REVIEWER = "REVIEWER"


class WorkflowStatus(StrEnum):
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class DocumentType(StrEnum):
    PAY_SLIP = "PAY_SLIP"
    BANK_STATEMENT = "BANK_STATEMENT"
    ID_PROOF = "ID_PROOF"


class DocumentStatus(StrEnum):
    UPLOADED = "UPLOADED"
    EXTRACTED = "EXTRACTED"
    EXTRACTION_FAILED = "EXTRACTION_FAILED"


class EventType(StrEnum):
    STATE_CHANGED = "STATE_CHANGED"
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    DOCUMENT_EXTRACTED = "DOCUMENT_EXTRACTED"
    AGENT_ACTION_PROPOSED = "AGENT_ACTION_PROPOSED"
    AGENT_ACTION_REJECTED = "AGENT_ACTION_REJECTED"
    TOOL_CALL_STARTED = "TOOL_CALL_STARTED"
    TOOL_CALL_SUCCEEDED = "TOOL_CALL_SUCCEEDED"
    TOOL_CALL_FAILED = "TOOL_CALL_FAILED"
    POLICY_EVALUATED = "POLICY_EVALUATED"
    INFORMATION_REQUESTED = "INFORMATION_REQUESTED"
    HUMAN_REVIEW_CREATED = "HUMAN_REVIEW_CREATED"
    DECISION_MADE = "DECISION_MADE"


class ValidationResult(StrEnum):
    ACCEPTED = "ACCEPTED"
    REJECTED_SCHEMA = "REJECTED_SCHEMA"
    REJECTED_PERMISSION = "REJECTED_PERMISSION"
    REJECTED_TRANSITION = "REJECTED_TRANSITION"


class ToolCallStatus(StrEnum):
    OK = "OK"
    ERROR = "ERROR"
    TIMEOUT = "TIMEOUT"


class ReviewStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    INFORMATION_REQUESTED = "INFORMATION_REQUESTED"
