from enum import StrEnum


class ApplicationState(StrEnum):
    RECEIVED = "RECEIVED"
    DOCUMENT_CHECK = "DOCUMENT_CHECK"
    INCOME_VERIFICATION = "INCOME_VERIFICATION"
    CREDIT_ANALYSIS = "CREDIT_ANALYSIS"
    RISK_ASSESSMENT = "RISK_ASSESSMENT"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    DECISION = "DECISION"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    MORE_INFORMATION_REQUIRED = "MORE_INFORMATION_REQUIRED"
    FAILED = "FAILED"


class Actor(StrEnum):
    SYSTEM = "SYSTEM"
    AGENT = "AGENT"
    APPLICANT = "APPLICANT"
    REVIEWER = "REVIEWER"
