from vero.domain.enums import Actor as A
from vero.domain.enums import ApplicationState as S

TERMINAL_STATES: frozenset[S] = frozenset({S.APPROVED, S.REJECTED, S.FAILED})

# The transition table. Each edge names the one actor permitted to drive it, which is
# how the agent is kept away from decisions and reviewer actions.
TRANSITION_ACTORS: dict[tuple[S, S], A] = {
    (S.RECEIVED, S.DOCUMENT_CHECK): A.SYSTEM,
    (S.DOCUMENT_CHECK, S.INCOME_VERIFICATION): A.AGENT,
    (S.DOCUMENT_CHECK, S.MORE_INFORMATION_REQUIRED): A.AGENT,
    (S.DOCUMENT_CHECK, S.FAILED): A.SYSTEM,
    (S.MORE_INFORMATION_REQUIRED, S.DOCUMENT_CHECK): A.APPLICANT,
    (S.MORE_INFORMATION_REQUIRED, S.FAILED): A.SYSTEM,
    (S.INCOME_VERIFICATION, S.CREDIT_ANALYSIS): A.SYSTEM,
    (S.INCOME_VERIFICATION, S.HUMAN_REVIEW): A.SYSTEM,
    (S.INCOME_VERIFICATION, S.FAILED): A.SYSTEM,
    (S.CREDIT_ANALYSIS, S.RISK_ASSESSMENT): A.SYSTEM,
    (S.CREDIT_ANALYSIS, S.FAILED): A.SYSTEM,
    (S.RISK_ASSESSMENT, S.DECISION): A.SYSTEM,
    (S.RISK_ASSESSMENT, S.HUMAN_REVIEW): A.SYSTEM,
    (S.HUMAN_REVIEW, S.DECISION): A.REVIEWER,
    (S.HUMAN_REVIEW, S.MORE_INFORMATION_REQUIRED): A.REVIEWER,
    (S.DECISION, S.APPROVED): A.SYSTEM,
    (S.DECISION, S.REJECTED): A.SYSTEM,
}

LEGAL_TRANSITIONS: frozenset[tuple[S, S]] = frozenset(TRANSITION_ACTORS)
