"""initial schema

Revision ID: 95fe5eb0cc30
Revises: 
Create Date: 2026-09-09 11:09:39.503607

"""
from typing import Sequence, Union

from alembic import op

from vero.db.schema import (
    APPEND_ONLY_FUNCTION,
    APPEND_ONLY_TRIGGER,
    APPEND_ONLY_TRUNCATE_TRIGGER,
)
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95fe5eb0cc30'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('applicant_name', sa.String(length=200), nullable=False),
    sa.Column('applicant_email', sa.String(length=320), nullable=False),
    sa.Column('gross_monthly_income', sa.BigInteger(), nullable=False),
    sa.Column('monthly_debt', sa.BigInteger(), nullable=False),
    sa.Column('requested_amount', sa.BigInteger(), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('annual_rate_bps', sa.Integer(), nullable=False),
    sa.CheckConstraint('gross_monthly_income > 0', name='ck_application_income_positive'),
    sa.CheckConstraint('monthly_debt >= 0', name='ck_application_debt_non_negative'),
    sa.CheckConstraint('requested_amount > 0', name='ck_application_amount_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('PAY_SLIP', 'BANK_STATEMENT', 'ID_PROOF', name='document_type', native_enum=False, length=32), nullable=False),
    sa.Column('storage_uri', sa.String(length=500), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'EXTRACTED', 'EXTRACTION_FAILED', name='document_status', native_enum=False, length=32), nullable=False),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extraction_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'content_hash', name='uq_document_content')
    )
    op.create_table('workflow_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('current_state', sa.Enum('RECEIVED', 'DOCUMENT_CHECK', 'INCOME_VERIFICATION', 'CREDIT_ANALYSIS', 'RISK_ASSESSMENT', 'HUMAN_REVIEW', 'DECISION', 'APPROVED', 'REJECTED', 'MORE_INFORMATION_REQUIRED', 'FAILED', name='application_state', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', name='workflow_status', native_enum=False, length=32), nullable=False),
    sa.Column('step_seq', sa.Integer(), nullable=False),
    sa.Column('document_request_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', name='uq_workflow_run_application')
    )
    op.create_table('agent_action',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('step_seq', sa.Integer(), nullable=False),
    sa.Column('state_at_proposal', sa.Enum('RECEIVED', 'DOCUMENT_CHECK', 'INCOME_VERIFICATION', 'CREDIT_ANALYSIS', 'RISK_ASSESSMENT', 'HUMAN_REVIEW', 'DECISION', 'APPROVED', 'REJECTED', 'MORE_INFORMATION_REQUIRED', 'FAILED', name='application_state', native_enum=False, length=32), nullable=False),
    sa.Column('proposed_action', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_result', sa.Enum('ACCEPTED', 'REJECTED_SCHEMA', 'REJECTED_PERMISSION', 'REJECTED_TRANSITION', name='validation_result', native_enum=False, length=32), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('human_review',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('triggered_gates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'INFORMATION_REQUESTED', name='review_status', native_enum=False, length=32), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_assessment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('credit_score', sa.Integer(), nullable=False),
    sa.Column('emi', sa.BigInteger(), nullable=False),
    sa.Column('disposable_income', sa.BigInteger(), nullable=False),
    sa.Column('dti_current', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('dti_proposed', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('lti', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('income_divergence', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('gate_bands', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overall', sa.Enum('PASS', 'REVIEW', 'FAIL', name='band', native_enum=False, length=32), nullable=False),
    sa.Column('outcome', sa.Enum('APPROVE', 'REJECT', 'REFER', name='policy_outcome', native_enum=False, length=32), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('STATE_CHANGED', 'DOCUMENT_UPLOADED', 'DOCUMENT_EXTRACTED', 'AGENT_ACTION_PROPOSED', 'AGENT_ACTION_REJECTED', 'TOOL_CALL_STARTED', 'TOOL_CALL_SUCCEEDED', 'TOOL_CALL_FAILED', 'POLICY_EVALUATED', 'INFORMATION_REQUESTED', 'HUMAN_REVIEW_CREATED', 'DECISION_MADE', name='event_type', native_enum=False, length=32), nullable=False),
    sa.Column('actor', sa.Enum('SYSTEM', 'AGENT', 'APPLICANT', 'REVIEWER', name='actor', native_enum=False, length=32), nullable=False),
    sa.Column('from_state', sa.Enum('RECEIVED', 'DOCUMENT_CHECK', 'INCOME_VERIFICATION', 'CREDIT_ANALYSIS', 'RISK_ASSESSMENT', 'HUMAN_REVIEW', 'DECISION', 'APPROVED', 'REJECTED', 'MORE_INFORMATION_REQUIRED', 'FAILED', name='application_state', native_enum=False, length=32), nullable=True),
    sa.Column('to_state', sa.Enum('RECEIVED', 'DOCUMENT_CHECK', 'INCOME_VERIFICATION', 'CREDIT_ANALYSIS', 'RISK_ASSESSMENT', 'HUMAN_REVIEW', 'DECISION', 'APPROVED', 'REJECTED', 'MORE_INFORMATION_REQUIRED', 'FAILED', name='application_state', native_enum=False, length=32), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_run_id', 'seq', name='uq_workflow_event_seq')
    )
    op.create_index('ix_workflow_event_application', 'workflow_event', ['application_id', 'seq'], unique=False)
    op.create_table('tool_call',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('agent_action_id', sa.UUID(), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('OK', 'ERROR', 'TIMEOUT', name='tool_call_status', native_enum=False, length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_action_id'], ['agent_action.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_tool_call_idempotency')
    )
    # ### end Alembic commands ###

    # The audit trail is only worth something if it cannot be quietly rewritten.
    op.execute(APPEND_ONLY_FUNCTION)
    op.execute(APPEND_ONLY_TRIGGER)
    op.execute(APPEND_ONLY_TRUNCATE_TRIGGER)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tool_call')
    op.drop_index('ix_workflow_event_application', table_name='workflow_event')
    op.drop_table('workflow_event')
    op.drop_table('risk_assessment')
    op.drop_table('human_review')
    op.drop_table('agent_action')
    op.drop_table('workflow_run')
    op.drop_table('document')
    op.drop_table('application')
    op.execute('DROP TRIGGER IF EXISTS workflow_event_no_truncate ON workflow_event')
    op.execute('DROP TRIGGER IF EXISTS workflow_event_append_only ON workflow_event')
    op.execute('DROP FUNCTION IF EXISTS vero_reject_mutation()')
    # ### end Alembic commands ###
