"""add synthetic credit score

Revision ID: d9e914c6042f
Revises: 95fe5eb0cc30
Create Date: 2026-09-09 11:20:54.203835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9e914c6042f'
down_revision: Union[str, Sequence[str], None] = '95fe5eb0cc30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('synthetic_credit_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'synthetic_credit_score')
    # ### end Alembic commands ###
