/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Applications */
        get: operations["list_applications_applications_get"];
        put?: never;
        /**
         * Create Application
         * @description Create an application and start work on it.
         *
         *     Returns immediately in RECEIVED rather than blocking until the workflow finishes:
         *     the run makes several model calls, and the caller should not wait on them.
         */
        post: operations["create_application_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Application Detail */
        get: operations["get_application_detail_applications__application_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Document */
        post: operations["upload_document_applications__application_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_applications__application_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Actor
         * @enum {string}
         */
        Actor: "SYSTEM" | "AGENT" | "APPLICANT" | "REVIEWER";
        /** ApplicationCreate */
        ApplicationCreate: {
            /** Applicant Name */
            applicant_name: string;
            /**
             * Applicant Email
             * Format: email
             */
            applicant_email: string;
            /** Gross Monthly Income Paise */
            gross_monthly_income_paise: number;
            /** Monthly Debt Paise */
            monthly_debt_paise: number;
            /** Requested Amount Paise */
            requested_amount_paise: number;
            /** Tenure Months */
            tenure_months: number;
            /** Synthetic Credit Score */
            synthetic_credit_score?: number | null;
        };
        /** ApplicationRead */
        ApplicationRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Applicant Name */
            applicant_name: string;
            /** Applicant Email */
            applicant_email: string;
            /** Gross Monthly Income Paise */
            gross_monthly_income_paise: number;
            /** Monthly Debt Paise */
            monthly_debt_paise: number;
            /** Requested Amount Paise */
            requested_amount_paise: number;
            /** Tenure Months */
            tenure_months: number;
            /** Annual Rate Bps */
            annual_rate_bps: number;
            state: components["schemas"]["ApplicationState"];
            status: components["schemas"]["WorkflowStatus"];
            /**
             * Documents
             * @default []
             */
            documents: components["schemas"]["DocumentRead"][];
            /**
             * Missing Documents
             * @default []
             */
            missing_documents: components["schemas"]["DocumentType"][];
            risk_assessment?: components["schemas"]["RiskAssessmentRead"] | null;
        };
        /**
         * ApplicationState
         * @enum {string}
         */
        ApplicationState: "RECEIVED" | "DOCUMENT_CHECK" | "INCOME_VERIFICATION" | "CREDIT_ANALYSIS" | "RISK_ASSESSMENT" | "HUMAN_REVIEW" | "DECISION" | "APPROVED" | "REJECTED" | "MORE_INFORMATION_REQUIRED" | "FAILED";
        /** ApplicationSummary */
        ApplicationSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Applicant Name */
            applicant_name: string;
            /** Requested Amount Paise */
            requested_amount_paise: number;
            /** Tenure Months */
            tenure_months: number;
            state: components["schemas"]["ApplicationState"];
            status: components["schemas"]["WorkflowStatus"];
        };
        /** Body_upload_document_applications__application_id__documents_post */
        Body_upload_document_applications__application_id__documents_post: {
            document_type: components["schemas"]["DocumentType"];
            /** File */
            file: string;
        };
        /** DocumentRead */
        DocumentRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            document_type: components["schemas"]["DocumentType"];
            status: components["schemas"]["DocumentStatus"];
            /** Extraction Confidence */
            extraction_confidence?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * DocumentStatus
         * @enum {string}
         */
        DocumentStatus: "UPLOADED" | "EXTRACTED" | "EXTRACTION_FAILED";
        /**
         * DocumentType
         * @enum {string}
         */
        DocumentType: "PAY_SLIP" | "BANK_STATEMENT" | "ID_PROOF";
        /**
         * EventType
         * @enum {string}
         */
        EventType: "STATE_CHANGED" | "DOCUMENT_UPLOADED" | "DOCUMENT_EXTRACTED" | "AGENT_ACTION_PROPOSED" | "AGENT_ACTION_REJECTED" | "TOOL_CALL_STARTED" | "TOOL_CALL_SUCCEEDED" | "TOOL_CALL_FAILED" | "POLICY_EVALUATED" | "INFORMATION_REQUESTED" | "HUMAN_REVIEW_CREATED" | "DECISION_MADE";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RiskAssessmentRead */
        RiskAssessmentRead: {
            /** Credit Score */
            credit_score: number;
            /** Emi */
            emi: number;
            /** Disposable Income */
            disposable_income: number;
            /** Dti Current */
            dti_current: string;
            /** Dti Proposed */
            dti_proposed: string;
            /** Lti */
            lti: string;
            /** Income Divergence */
            income_divergence: string;
            /** Gate Bands */
            gate_bands: {
                [key: string]: string;
            };
            /** Overall */
            overall: string;
            /** Outcome */
            outcome: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkflowEventRead */
        WorkflowEventRead: {
            /** Seq */
            seq: number;
            event_type: components["schemas"]["EventType"];
            actor: components["schemas"]["Actor"];
            from_state?: components["schemas"]["ApplicationState"] | null;
            to_state?: components["schemas"]["ApplicationState"] | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * WorkflowStatus
         * @enum {string}
         */
        WorkflowStatus: "RUNNING" | "PAUSED" | "COMPLETED" | "FAILED";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_applications_applications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationSummary"][];
                };
            };
        };
    };
    create_application_applications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_application_detail_applications__application_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_applications__application_id__documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_applications__application_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_applications__application_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowEventRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
